# Generated by Django 4.2.7 on 2023-11-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
