# Generated by Django 4.2.3 on 2023-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_bebida_imagen_comida_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comida',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
